class CreateCities < ActiveRecord::Migration
  def self.up
    create_table :cities do |t|
      t.string :name
      t.string :code

      t.timestamps
    end


    City.create(:name => "Aiglun", :code => "06910")
    City.create(:name => "Amirat", :code => "06910")
    City.create(:name => "Andon", :code => "06750")
    City.create(:name => "Antibes", :code => "06600")
    City.create(:name => "Antibes", :code => "06160")
    City.create(:name => "Ascros", :code => "06260")
    City.create(:name => "Aspremont", :code => "06790")
    City.create(:name => "Auribeau Sur Siagne", :code => "06810")
    City.create(:name => "Auron", :code => "06660")
    City.create(:name => "Auvare", :code => "06260")
    City.create(:name => "Bairols", :code => "06420")
    City.create(:name => "Beaulieu Sur Mer", :code => "06310")
    City.create(:name => "Beausoleil", :code => "06240")
    City.create(:name => "Belvedere", :code => "06450")
    City.create(:name => "Bendejun", :code => "06390")
    City.create(:name => "Berre Des Alpes", :code => "06390")
    City.create(:name => "Beuil", :code => "06470")
    City.create(:name => "Bezaudun Les Alpes", :code => "06510")
    City.create(:name => "Biot", :code => "06410")
    City.create(:name => "Blausasc", :code => "06440")
    City.create(:name => "Bonson", :code => "06830")
    City.create(:name => "Bouyon", :code => "06510")
    City.create(:name => "Breil Sur Roya", :code => "06540")
    City.create(:name => "Brianconnet", :code => "06850")
    City.create(:name => "Cabris", :code => "06530")
    City.create(:name => "Cagnes Sur Mer", :code => "06800")
    City.create(:name => "Caille", :code => "06750")
    City.create(:name => "Cannes", :code => "06150")
    City.create(:name => "Cannes", :code => "06400")
    City.create(:name => "Cantaron", :code => "06340")
    City.create(:name => "Cap D'Ail", :code => "06320")
    City.create(:name => "Cap D'Antibes", :code => "06160")
    City.create(:name => "Carnoles", :code => "06190")
    City.create(:name => "Carros", :code => "06510")
    City.create(:name => "Castagniers", :code => "06670")
    City.create(:name => "Castellar", :code => "06500")
    City.create(:name => "Castillon", :code => "06500")
    City.create(:name => "Caussols", :code => "06460")
    City.create(:name => "Chateauneuf D'Entraunes", :code => "06470")
    City.create(:name => "Chateauneuf Grasse", :code => "06740")
    City.create(:name => "Chateauneuf Villevieille", :code => "06390")
    City.create(:name => "Cipieres", :code => "06620")
    City.create(:name => "Clans", :code => "06420")
    City.create(:name => "Coaraze", :code => "06390")
    City.create(:name => "Collongues", :code => "06910")
    City.create(:name => "Colomars", :code => "06670")
    City.create(:name => "Consegudes", :code => "06510")
    City.create(:name => "Contes", :code => "06390")
    City.create(:name => "Courmes", :code => "06620")
    City.create(:name => "Coursegoules", :code => "06140")
    City.create(:name => "Cros De Cagnes", :code => "06800")
    City.create(:name => "Cuebris", :code => "06910")
    City.create(:name => "Daluis", :code => "06470")
    City.create(:name => "Drap", :code => "06340")
    City.create(:name => "Duranus", :code => "06670")
    City.create(:name => "Entraunes", :code => "06470")
    City.create(:name => "Escragnolles", :code => "06460")
    City.create(:name => "Esteing", :code => "06470")
    City.create(:name => "Eze", :code => "06360")
    City.create(:name => "Falicon", :code => "06950")
    City.create(:name => "Fontan", :code => "06540")
    City.create(:name => "Gars", :code => "06850")
    City.create(:name => "Gattieres", :code => "06510")
    City.create(:name => "Gilette", :code => "06830")
    City.create(:name => "Gorbio", :code => "06500")
    City.create(:name => "Gourdon", :code => "06620")
    City.create(:name => "Grasse", :code => "06130")
    City.create(:name => "Grasse", :code => "06520")
    City.create(:name => "Greolieres", :code => "06620")
    City.create(:name => "Guillaumes", :code => "06470")
    City.create(:name => "Ilonse", :code => "06420")
    City.create(:name => "Isola", :code => "06420")
    City.create(:name => "Juan Les Pins", :code => "06160")
    City.create(:name => "L'Escarene", :code => "06440")
    City.create(:name => "La Bocca", :code => "06150")
    City.create(:name => "La Bollene Vesubie", :code => "06450")
    City.create(:name => "La Brigue", :code => "06430")
    City.create(:name => "La Colle Sur Loup", :code => "06480")
    City.create(:name => "La Croix Sur Roudoule", :code => "06260")
    City.create(:name => "La Fontonne", :code => "06600")
    City.create(:name => "La Gaude", :code => "06610")
    City.create(:name => "La Grave De Peille", :code => "06440")
    City.create(:name => "La Napoule", :code => "06210")
    City.create(:name => "La Penne", :code => "06260")
    City.create(:name => "La Rochette", :code => "06260")
    City.create(:name => "La Roquette Sur Siagne", :code => "06550")
    City.create(:name => "La Roquette Sur Var", :code => "06670")
    City.create(:name => "La Tour", :code => "06710")
    City.create(:name => "La Trinite", :code => "06340")
    City.create(:name => "La Turbie", :code => "06320")
    City.create(:name => "Lantosque", :code => "06450")
    City.create(:name => "Le Bar Sur Loup", :code => "06620")
    City.create(:name => "Le Boreon", :code => "06450")
    City.create(:name => "Le Broc", :code => "06510")
    City.create(:name => "Le Cannet", :code => "06110")
    City.create(:name => "Le Golfe Juan", :code => "06220")
    City.create(:name => "Le Logis Du Pin", :code => "06750")
    City.create(:name => "Le Mas", :code => "06910")
    City.create(:name => "Le Plan De Grasse", :code => "06130")
    City.create(:name => "Le Rouret", :code => "06650")
    City.create(:name => "Le Tignet", :code => "06530")
    City.create(:name => "Les Ferres", :code => "06510")
    City.create(:name => "Les Mujouls", :code => "06910")
    City.create(:name => "Levens", :code => "06670")
    City.create(:name => "Lieuche", :code => "06260")
    City.create(:name => "Luceram", :code => "06440")
    City.create(:name => "Magagnosc", :code => "06520")
    City.create(:name => "Malaussene", :code => "06710")
    City.create(:name => "Mandelieu La Napoule", :code => "06210")
    City.create(:name => "Marie", :code => "06420")
    City.create(:name => "Massoins", :code => "06710")
    City.create(:name => "Menton", :code => "06500")
    City.create(:name => "Miramar", :code => "06590")
    City.create(:name => "Mouans Sartoux", :code => "06370")
    City.create(:name => "Mougins", :code => "06250")
    City.create(:name => "Moulinet", :code => "06380")
    City.create(:name => "Nice", :code => "06100")
    City.create(:name => "Nice", :code => "06000")
    City.create(:name => "Nice", :code => "06300")
    City.create(:name => "Nice", :code => "06200")
    City.create(:name => "Opio", :code => "06650")
    City.create(:name => "Pegomas", :code => "06580")
    City.create(:name => "Peille", :code => "06440")
    City.create(:name => "Peillon", :code => "06440")
    City.create(:name => "Peira Cava", :code => "06440")
    City.create(:name => "Peone", :code => "06470")
    City.create(:name => "Peymeinade", :code => "06530")
    City.create(:name => "Pierlas", :code => "06260")
    City.create(:name => "Pierrefeu", :code => "06910")
    City.create(:name => "Plan Du Var", :code => "06670")
    City.create(:name => "Plascassier", :code => "06130")
    City.create(:name => "Puget Rostang", :code => "06260")
    City.create(:name => "Puget Theniers", :code => "06260")
    City.create(:name => "Revest Les Roches", :code => "06830")
    City.create(:name => "Rigaud", :code => "06260")
    City.create(:name => "Rimplas", :code => "06420")
    City.create(:name => "Rocheville", :code => "06110")
    City.create(:name => "Roquebilliere", :code => "06450")
    City.create(:name => "Roquebrune Cap Martin", :code => "06190")
    City.create(:name => "Roquefort Les Pins", :code => "06330")
    City.create(:name => "Roquesteron", :code => "06910")
    City.create(:name => "Roquesteron Grasse", :code => "06910")
    City.create(:name => "Roubion", :code => "06420")
    City.create(:name => "Roure", :code => "06420")
    City.create(:name => "Sallagriffon", :code => "06910")
    City.create(:name => "Saorge", :code => "06540")
    City.create(:name => "Sauze", :code => "06470")
    City.create(:name => "Seranon", :code => "06750")
    City.create(:name => "Sigale", :code => "06910")
    City.create(:name => "Sophia Antipolis", :code => "06560")
    City.create(:name => "Sospel", :code => "06380")
    City.create(:name => "Speracedes", :code => "06530")
    City.create(:name => "St Andre", :code => "06730")
    City.create(:name => "St Antonin", :code => "06260")
    City.create(:name => "St Auban", :code => "06850")
    City.create(:name => "St Blaise", :code => "06670")
    City.create(:name => "St Cezaire Sur Siagne", :code => "06530")
    City.create(:name => "St Dalmas De Tende", :code => "06430")
    City.create(:name => "St Dalmas Le Selvage", :code => "06660")
    City.create(:name => "St Etienne De Tinee", :code => "06660")
    City.create(:name => "St Isidore", :code => "06200")
    City.create(:name => "St Jean Cap Ferrat", :code => "06230")
    City.create(:name => "St Jean La Riviere", :code => "06450")
    City.create(:name => "St Jeannet", :code => "06640")
    City.create(:name => "St Laurent Du Var", :code => "06700")
    City.create(:name => "St Leger", :code => "06260")
    City.create(:name => "St Martin D'Entraunes", :code => "06470")
    City.create(:name => "St Martin Du Var", :code => "06670")
    City.create(:name => "St Martin Vesubie", :code => "06450")
    City.create(:name => "St Paul", :code => "06570")
    City.create(:name => "St Pierre", :code => "06260")
    City.create(:name => "St Roman De Bellet", :code => "06200")
    City.create(:name => "St Sauveur Sur Tinee", :code => "06420")
    City.create(:name => "St Vallier De Thiey", :code => "06460")
    City.create(:name => "Ste Agnes", :code => "06500")
    City.create(:name => "Tende", :code => "06430")
    City.create(:name => "Theoule Sur Mer", :code => "06590")
    City.create(:name => "Thiery", :code => "06710")
    City.create(:name => "Thorenc", :code => "06750")
    City.create(:name => "Toudon", :code => "06830")
    City.create(:name => "Touet De L'Escarene", :code => "06440")
    City.create(:name => "Touet Sur Var", :code => "06710")
    City.create(:name => "Tourette Du Chateau", :code => "06830")
    City.create(:name => "Tournefort", :code => "06710")
    City.create(:name => "Tourrette Levens", :code => "06690")
    City.create(:name => "Tourrettes Sur Loup", :code => "06140")
    City.create(:name => "Utelle", :code => "06450")
    City.create(:name => "Valberg", :code => "06470")
    City.create(:name => "Valbonne", :code => "06560")
    City.create(:name => "Valdeblore", :code => "06420")
    City.create(:name => "Valderoure", :code => "06750")
    City.create(:name => "Vallauris", :code => "06220")
    City.create(:name => "Venanson", :code => "06450")
    City.create(:name => "Vence", :code => "06140")
    City.create(:name => "Villars Sur Var", :code => "06710")
    City.create(:name => "Villefranche Sur Mer", :code => "06230")
    City.create(:name => "Villeneuve D'Entraunes", :code => "06470")
    City.create(:name => "Villeneuve Loubet", :code => "06270")
  end
  
  def self.down
    drop_table :cities
  end
end
