class CreateCountries < ActiveRecord::Migration
  def self.up
    create_table :countries do |t|
      t.string :name
      t.string :code
      t.timestamps
    end

    # Insert the initial elements
    Country.create(:name => "Afghanistan", :code => "93")
    Country.create(:name => "Afrique du Sud", :code => "27")
    Country.create(:name => "Albanie", :code => "355")
    Country.create(:name => "Algérie", :code => "213")
    Country.create(:name => "Allemagne", :code => "49")
    Country.create(:name => "Andorre", :code => "376")
    Country.create(:name => "Angola", :code => "244")
    Country.create(:name => "Anguilla", :code => "11")
    Country.create(:name => "Antigua-et-Barbuda", :code => "11")
    Country.create(:name => "Antilles néerlandaises", :code => "599")
    Country.create(:name => "Arabie saoudite", :code => "966")
    Country.create(:name => "Argentine", :code => "54")
    Country.create(:name => "Arménie", :code => "374")
    Country.create(:name => "Aruba", :code => "297")
    Country.create(:name => "Ascension", :code => "247")
    Country.create(:name => "Australie", :code => "61")
    Country.create(:name => "Palestine", :code => "970")
    Country.create(:name => "Autriche", :code => "43")
    Country.create(:name => "Azerbaïdjan", :code => "994")
    Country.create(:name => "Bahamas", :code => "1")
    Country.create(:name => "Bahreïn", :code => "973")
    Country.create(:name => "Bangladesh", :code => "880")
    Country.create(:name => "Barbade", :code => "11")
    Country.create(:name => "Belgique", :code => "32")
    Country.create(:name => "Belize", :code => "501")
    Country.create(:name => "Bénin", :code => "229")
    Country.create(:name => "Bermudes", :code => "11")
    Country.create(:name => "Bhoutan", :code => "975")
    Country.create(:name => "Biélorussie", :code => "375")
    Country.create(:name => "Birmanie", :code => "95")
    Country.create(:name => "Bolivie", :code => "591")
    Country.create(:name => "Bosnie-Herzégovine", :code => "387")
    Country.create(:name => "Botswana", :code => "267")
    Country.create(:name => "Brésil", :code => "55")
    Country.create(:name => "Brunei", :code => "673")
    Country.create(:name => "Bulgarie", :code => "359")
    Country.create(:name => "Burkina Faso", :code => "226")
    Country.create(:name => "Burundi", :code => "257")
    Country.create(:name => "Cambodge", :code => "855")
    Country.create(:name => "Cameroun", :code => "237")
    Country.create(:name => "Canada", :code => "11")
    Country.create(:name => "Cap-Vert", :code => "238")
    Country.create(:name => "Îles Caïmans", :code => "11")
    Country.create(:name => "République centrafricaine", :code => "236")
    Country.create(:name => "Chili", :code => "56")
    Country.create(:name => "Chine", :code => "86")
    Country.create(:name => "Chypre", :code => "357")
    Country.create(:name => "Colombie", :code => "57")
    Country.create(:name => "Comores", :code => "269")
    Country.create(:name => "République démocratique du Congo", :code => "243")
    Country.create(:name => "République du Congo", :code => "242")
    Country.create(:name => "Îles Cook", :code => "682")
    Country.create(:name => "Corée du Nord", :code => "850")
    Country.create(:name => "Corée du Sud", :code => "82")
    Country.create(:name => "Costa Rica", :code => "506")
    Country.create(:name => "Côte d'Ivoire", :code => "225")
    Country.create(:name => "Croatie", :code => "385")
    Country.create(:name => "Cuba", :code => "53")
    Country.create(:name => "Danemark", :code => "45")
    Country.create(:name => "Diego Garcia", :code => "0")
    Country.create(:name => "Djibouti", :code => "253")
    Country.create(:name => "République dominicaine", :code => "11")
    Country.create(:name => "Dominique", :code => "11")
    Country.create(:name => "Égypte", :code => "20")
    Country.create(:name => "Émirats arabes unis", :code => "971")
    Country.create(:name => "Équateur", :code => "593")
    Country.create(:name => "Érythrée", :code => "291")
    Country.create(:name => "Espagne", :code => "34")
    Country.create(:name => "Estonie", :code => "372")
    Country.create(:name => "États-Unis", :code => "11")
    Country.create(:name => "Éthiopie", :code => "251")
    Country.create(:name => "Îles Féro", :code => "298")
    Country.create(:name => "Fidji", :code => "679")
    Country.create(:name => "Finlande", :code => "358")
    Country.create(:name => "France", :code => "33")
    Country.create(:name => "Gabon", :code => "241")
    Country.create(:name => "Gambie", :code => "220")
    Country.create(:name => "Géorgie", :code => "995")
    Country.create(:name => "Ghana", :code => "233")
    Country.create(:name => "Gibraltar", :code => "350")
    Country.create(:name => "Grèce", :code => "30")
    Country.create(:name => "Grenade", :code => "11")
    Country.create(:name => "Groenland", :code => "299")
    Country.create(:name => "Guadeloupe", :code => "590")
    Country.create(:name => "Guam", :code => "11")
    Country.create(:name => "Guatemala", :code => "502")
    Country.create(:name => "Guinée", :code => "224")
    Country.create(:name => "Guinée équatoriale", :code => "240")
    Country.create(:name => "Guinée-Bissau", :code => "245")
    Country.create(:name => "Guyana", :code => "592")
    Country.create(:name => "Guyane", :code => "594")
    Country.create(:name => "Haïti", :code => "509")
    Country.create(:name => "Honduras", :code => "504")
    Country.create(:name => "Hong Kong", :code => "852")
    Country.create(:name => "Hongrie", :code => "36")
    Country.create(:name => "Inde", :code => "91")
    Country.create(:name => "Indonésie", :code => "62")
    Country.create(:name => "Irak", :code => "964")
    Country.create(:name => "Iran", :code => "98")
    Country.create(:name => "Irlande", :code => "353")
    Country.create(:name => "Islande", :code => "354")
    Country.create(:name => "Israël", :code => "972")
    Country.create(:name => "Italie", :code => "39")
    Country.create(:name => "Jamaïque", :code => "11")
    Country.create(:name => "Japon", :code => "81")
    Country.create(:name => "Jordanie", :code => "962")
    Country.create(:name => "Kazakhstan", :code => "7")
    Country.create(:name => "Kenya", :code => "254")
    Country.create(:name => "Kirghizistan", :code => "996")
    Country.create(:name => "Kiribati", :code => "686")
    Country.create(:name => "Kosovo", :code => "386")
    Country.create(:name => "Koweït", :code => "965")
    Country.create(:name => "Laos", :code => "856")
    Country.create(:name => "Lesotho", :code => "266")
    Country.create(:name => "Lettonie", :code => "371")
    Country.create(:name => "Liban", :code => "961")
    Country.create(:name => "Liberia", :code => "231")
    Country.create(:name => "Libye", :code => "218")
    Country.create(:name => "Liechtenstein", :code => "423")
    Country.create(:name => "Lituanie", :code => "370")
    Country.create(:name => "Luxembourg", :code => "352")
    Country.create(:name => "Macao", :code => "853")
    Country.create(:name => "Macédoine", :code => "389")
    Country.create(:name => "Madagascar", :code => "261")
    Country.create(:name => "Malaisie", :code => "60")
    Country.create(:name => "Malawi", :code => "265")
    Country.create(:name => "Maldives", :code => "960")
    Country.create(:name => "Mali", :code => "223")
    Country.create(:name => "Îles Malouines", :code => "500")
    Country.create(:name => "Malte", :code => "356")
    Country.create(:name => "Îles Mariannes du Nord", :code => "11")
    Country.create(:name => "Maroc", :code => "212")
    Country.create(:name => "Marshall", :code => "692")
    Country.create(:name => "Martinique", :code => "596")
    Country.create(:name => "Maurice", :code => "230")
    Country.create(:name => "Mauritanie", :code => "222")
    Country.create(:name => "Mayotte", :code => "262")
    Country.create(:name => "Mexique", :code => "52")
    Country.create(:name => "Micronésie", :code => "691")
    Country.create(:name => "Moldavie", :code => "373")
    Country.create(:name => "Monaco", :code => "377")
    Country.create(:name => "Mongolie", :code => "976")
    Country.create(:name => "Monténégro", :code => "382")
    Country.create(:name => "Montserrat", :code => "11")
    Country.create(:name => "Mozambique", :code => "258")
    Country.create(:name => "Namibie", :code => "264")
    Country.create(:name => "Nauru", :code => "674")
    Country.create(:name => "Népal", :code => "977")
    Country.create(:name => "Nicaragua", :code => "505")
    Country.create(:name => "Niger", :code => "227")
    Country.create(:name => "Nigeria", :code => "234")
    Country.create(:name => "Niue", :code => "683")
    Country.create(:name => "Norvège", :code => "47")
    Country.create(:name => "Nouvelle-Calédonie", :code => "687")
    Country.create(:name => "Nouvelle-Zélande", :code => "64")
    Country.create(:name => "Oman", :code => "968")
    Country.create(:name => "Ouganda", :code => "256")
    Country.create(:name => "Ouzbékistan", :code => "998")
    Country.create(:name => "Pakistan", :code => "92")
    Country.create(:name => "Palaos", :code => "680")
    Country.create(:name => "Panam", :code => "507")
    Country.create(:name => "Papouasie-Nouvelle-Guinée", :code => "675")
    Country.create(:name => "Paraguay", :code => "595")
    Country.create(:name => "Pays-Bas", :code => "31")
    Country.create(:name => "Pérou", :code => "51")
    Country.create(:name => "Philippines", :code => "63")
    Country.create(:name => "Pologne", :code => "48")
    Country.create(:name => "Polynésie française", :code => "689")
    Country.create(:name => "Porto Rico", :code => "11")
    Country.create(:name => "Portugal", :code => "351")
    Country.create(:name => "Qatar", :code => "974")
    Country.create(:name => "La Réunion", :code => "262")
    Country.create(:name => "Roumanie", :code => "40")
    Country.create(:name => "Royaume-Uni", :code => "44")
    Country.create(:name => "Russie", :code => "7")
    Country.create(:name => "Rwanda", :code => "250")
    Country.create(:name => "Saint-Christophe-et-Niévès", :code => "11")
    Country.create(:name => "Sainte-Hélène, île", :code => "290")
    Country.create(:name => "Sainte-Lucie", :code => "11")
    Country.create(:name => "Saint-Marin", :code => "378")
    Country.create(:name => "Saint-Pierre-et-Miquelon", :code => "508")
    Country.create(:name => "Saint-Vincent-et-les Grenadines", :code => "11")
    Country.create(:name => "Salomon", :code => "677")
    Country.create(:name => "Salvador", :code => "503")
    Country.create(:name => "Samoa", :code => "685")
    Country.create(:name => "Samoa américaines", :code => "11")
    Country.create(:name => "Sao Tomé-et-Principe", :code => "239")
    Country.create(:name => "Sénégal", :code => "221")
    Country.create(:name => "Serbie", :code => "381")
    Country.create(:name => "Seychelles", :code => "248")
    Country.create(:name => "Sierra Leone", :code => "232")
    Country.create(:name => "Singapour", :code => "65")
    Country.create(:name => "Slovaquie", :code => "421")
    Country.create(:name => "Slovénie", :code => "386")
    Country.create(:name => "Somalie", :code => "252")
    Country.create(:name => "Soudan", :code => "249")
    Country.create(:name => "Sri Lanka", :code => "94")
    Country.create(:name => "Suède", :code => "46")
    Country.create(:name => "Suisse", :code => "41")
    Country.create(:name => "Suriname", :code => "597")
    Country.create(:name => "Swaziland", :code => "268")
    Country.create(:name => "Syrie", :code => "963")
    Country.create(:name => "Tadjikistan", :code => "992")
    Country.create(:name => "Tanzanie", :code => "255")
    Country.create(:name => "Taïwan", :code => "886")
    Country.create(:name => "Tchad", :code => "235")
    Country.create(:name => "République tchèque", :code => "420")
    Country.create(:name => "Thaïlande", :code => "66")
    Country.create(:name => "Timor oriental", :code => "670")
    Country.create(:name => "Togo", :code => "228")
    Country.create(:name => "Tokelau", :code => "690")
    Country.create(:name => "Tonga", :code => "676")
    Country.create(:name => "Trinité-et-Tobago", :code => "11")
    Country.create(:name => "Tunisie", :code => "216")
    Country.create(:name => "Turkménistan", :code => "993")
    Country.create(:name => "Îles Turques-et-Caïques", :code => "11")
    Country.create(:name => "Turquie", :code => "90")
    Country.create(:name => "Tuvalu", :code => "688")
    Country.create(:name => "Ukraine", :code => "380")
    Country.create(:name => "Uruguay", :code => "598")
    Country.create(:name => "Vanuatu", :code => "678")
    Country.create(:name => "Vatican", :code => "379")
    Country.create(:name => "Venezuela", :code => "58")
    Country.create(:name => "Îles Vierges américaines", :code => "11")
    Country.create(:name => "Îles Vierges britanniques", :code => "11")
    Country.create(:name => "Viêt Nam", :code => "84")
    Country.create(:name => "Wallis-et-Futuna", :code => "681")
    Country.create(:name => "Yémen", :code => "967")
    Country.create(:name => "Zambie", :code => "260")
    Country.create(:name => "Zimbabwe", :code => "263")

  end

  def self.down
    drop_table :countries
  end
end
